/*
	This file is part of Desperion.
	Copyright 2010, 2011 LittleScaraby, Nekkro

    Desperion is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Desperion is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Desperion.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef __STDAFX__
#define __STDAFX__

#define GAME_VERSION_MAJOR 0
#define GAME_VERSION_MINOR 8
#define GAME_VERSION_REVISION 3

#define REQUIRED_SHARED_VERSION_MAJOR 0
#define REQUIRED_SHARED_VERSION_MINOR 0
#define REQUIRED_SHARED_VERSION_REVISION 3

#include "../Shared/StdAfx.h"

#if SHARED_VERSION_MAJOR != REQUIRED_SHARED_VERSION_MAJOR || SHARED_VERSION_MINOR != REQUIRED_SHARED_VERSION_MINOR \
	|| SHARED_VERSION_REVISION != REQUIRED_SHARED_VERSION_REVISION
#pragma error("This Shared version isn't compatible with this Desperion version.");
#endif

#include "ProtocolTypeManager.h"
#include "ConfigDefaults.h"
#include "World.h"
#include "Master.h"
#include "CharacterMinimals.h"
#include "ConditionsParser.h"
#include "DofusUtils.h"

#include "../Models/CharacterBaseCharacteristic.h"
#include "../Models/ObjectEffect.h"
#include "../Models/ObjectEffectInteger.h"
#include "../Models/ObjectEffectDice.h"
#include "../Models/ObjectEffectCreature.h"
#include "../Models/ObjectEffectDate.h"
#include "../Models/ObjectEffectDuration.h"
#include "../Models/ObjectEffectLadder.h"
#include "../Models/ObjectEffectMinMax.h"
#include "../Models/ObjectEffectMount.h"
#include "../Models/ObjectEffectString.h"
#include "../Models/SubEntity.h"
#include "../Models/EntityLook.h"
#include "../Models/CharacterMinimalInformations.h"
#include "../Models/CharacterMinimalPlusLookInformations.h"
#include "../Models/CharacterBaseInformations.h"
#include "../Models/EntityDispositionInformations.h"
#include "../Models/GameContextActorInformations.h"
#include "../Models/GameRolePlayActorInformations.h"
#include "../Models/GameRolePlayNamedActorInformations.h"
#include "../Models/ActorRestrictionsInformations.h"
#include "../Models/HumanInformations.h"
#include "../Models/GameRolePlayHumanoidInformations.h"
#include "../Models/ActorAlignmentInformations.h"
#include "../Models/GameRolePlayCharacterInformations.h"
#include "../Models/Item.h"
#include "../Models/ObjectItem.h"
#include "../Models/GoldItem.h"
#include "../Models/ActorExtendedAlignmentInformations.h"
#include "../Models/CharacterSpellModification.h"
#include "../Models/CharacterCharacteristicsInformations.h"
#include "../Models/BasicGuildInformations.h"
#include "../Models/AbstractContactInformations.h"
#include "../Models/FriendInformations.h"
#include "../Models/FriendOnlineInformations.h"
#include "../Models/IgnoredInformations.h"
#include "../Models/IgnoredOnlineInformations.h"
#include "../Models/ObjectItemQuantity.h"
#include "../Models/MapObstacle.h"
#include "../Models/StatedElement.h"
#include "../Models/HouseInformations.h"
#include "../Models/InteractiveElementSkill.h"
#include "../Models/InteractiveElement.h"
#include "../Models/AbstractFightTeamInformations.h"
#include "../Models/FightTeamMemberInformations.h"
#include "../Models/FightTeamInformations.h"
#include "../Models/FightOptionsInformations.h"
#include "../Models/FightCommonInformations.h"

#include "CharacterStats.h"
#include "PlayerItem.h"
#include "Item.h"
#include "Weapon.h"
#include "Map.h"
#include "Path.h"
#include "GameClient.h"

#include "../Messages/AuthenticationTicketMessage.h"
#include "../Messages/AuthenticationTicketRefusedMessage.h"
#include "../Messages/AuthenticationTicketAcceptedMessage.h"
#include "../Messages/AccountCapabilitiesMessage.h"
#include "../Messages/CharactersListRequestMessage.h"
#include "../Messages/CharactersListMessage.h"
#include "../Messages/CharacterDeletionRequestMessage.h"
#include "../Messages/CharacterDeletionErrorMessage.h"
#include "../Messages/CharacterNameSuggestionRequestMessage.h"
#include "../Messages/ServerOptionalFeaturesMessage.h"
#include "../Messages/HelloGameMessage.h"
#include "../Messages/CharacterNameSuggestionFailureMessage.h"
#include "../Messages/CharacterNameSuggestionSuccessMessage.h"
#include "../Messages/CharacterSelectionMessage.h"
#include "../Messages/CharacterSelectedErrorMessage.h"
#include "../Messages/CharacterSelectedSuccessMessage.h"
#include "../Messages/CharacterCreationRequestMessage.h"
#include "../Messages/GameContextDestroyMessage.h"
#include "../Messages/GameContextCreateRequestMessage.h"
#include "../Messages/GameContextCreateMessage.h"
#include "../Messages/InventoryContentMessage.h"
#include "../Messages/InventoryWeightMessage.h"
#include "../Messages/CurrentMapMessage.h"
#include "../Messages/TextInformationMessage.h"
#include "../Messages/MapInformationsRequestMessage.h"
#include "../Messages/GameMapMovementRequestMessage.h"
#include "../Messages/GameMapMovementMessage.h"
#include "../Messages/GameMapMovementConfirmMessage.h"
#include "../Messages/ChangeMapMessage.h"
#include "../Messages/BasicNoOperationMessage.h"
#include "../Messages/AdminCommandMessage.h"
#include "../Messages/AdminQuietCommandMessage.h"
#include "../Messages/ConsoleCommandsListMessage.h"
#include "../Messages/ConsoleMessage.h"
#include "../Messages/GameContextRemoveElementMessage.h"
#include "../Messages/ChatAbstractClientMessage.h"
#include "../Messages/ChatAbstractServerMessage.h"
#include "../Messages/ChatClientMultiMessage.h"
#include "../Messages/ChatClientMultiWithObjectMessage.h"
#include "../Messages/ChatClientPrivateMessage.h"
#include "../Messages/ChatClientPrivateWithObjectMessage.h"
#include "../Messages/ChatErrorMessage.h"
#include "../Messages/ChatServerCopyMessage.h"
#include "../Messages/ChatServerCopyWithObjectMessage.h"
#include "../Messages/ChatServerMessage.h"
#include "../Messages/ChatServerWithObjectMessage.h"
#include "../Messages/ChatAdminServerMessage.h"
#include "../Messages/GoldAddedMessage.h"
#include "../Messages/LivingObjectChangeSkinRequestMessage.h"
#include "../Messages/LivingObjectDissociateMessage.h"
#include "../Messages/LivingObjectMessageMessage.h"
#include "../Messages/LivingObjectMessageRequestMessage.h"
#include "../Messages/ObjectAddedMessage.h"
#include "../Messages/ObjectDeletedMessage.h"
#include "../Messages/ObjectDeleteMessage.h"
#include "../Messages/ObjectDropMessage.h"
#include "../Messages/ObjectErrorMessage.h"
#include "../Messages/ObjectFeedMessage.h"
#include "../Messages/ObjectModifiedMessage.h"
#include "../Messages/ObjectMovementMessage.h"
#include "../Messages/ObjectQuantityMessage.h"
#include "../Messages/ObjectsAddedMessage.h"
#include "../Messages/ObjectsDeletedMessage.h"
#include "../Messages/ObjectSetPositionMessage.h"
#include "../Messages/ObjectsQuantityMessage.h"
#include "../Messages/ObjectUseMessage.h"
#include "../Messages/ObjectUseMultipleMessage.h"
#include "../Messages/ObjectUseOnCellMessage.h"
#include "../Messages/ObjectUseOnCharacterMessage.h"
#include "../Messages/SetUpdateMessage.h"
#include "../Messages/GameContextRefreshEntityLookMessage.h"
#include "../Messages/ObjectGroundAddedMessage.h"
#include "../Messages/ObjectGroundListAddedMessage.h"
#include "../Messages/ObjectGroundRemovedMessage.h"
#include "../Messages/ObjectGroundRemovedMultipleMessage.h"
#include "../Messages/CharacterCreationResultMessage.h"
#include "../Messages/BasicPingMessage.h"
#include "../Messages/BasicPongMessage.h"
#include "../Messages/BasicTimeMessage.h"
#include "../Messages/BasicDateMessage.h"
#include "../Messages/ProtocolRequired.h"
#include "../Messages/TrustStatusMessage.h"
#include "../Messages/EnabledChannelsMessage.h"
#include "../Messages/ChannelEnablingChangeMessage.h"
#include "../Messages/ChannelEnablingMessage.h"
#include "../Messages/MoodSmileyResultMessage.h"
#include "../Messages/MoodSmileyRequestMessage.h"
#include "../Messages/ChatSmileyMessage.h"
#include "../Messages/LocalizedChatSmileyMessage.h"
#include "../Messages/ChatSmileyRequestMessage.h"
#include "../Messages/BasicWhoAmIRequestMessage.h"
#include "../Messages/BasicWhoIsMessage.h"
#include "../Messages/BasicWhoIsNoMatchMessage.h"
#include "../Messages/BasicWhoIsRequestMessage.h"
#include "../Messages/NumericWhoIsMessage.h"
#include "../Messages/NumericWhoIsRequestMessage.h"
#include "../Messages/IgnoredListMessage.h"
#include "../Messages/IgnoredGetListMessage.h"
#include "../Messages/IgnoredDeleteResultMessage.h"
#include "../Messages/IgnoredDeleteRequestMessage.h"
#include "../Messages/IgnoredAddRequestMessage.h"
#include "../Messages/IgnoredAddFailureMessage.h"
#include "../Messages/IgnoredAddedMessage.h"
#include "../Messages/GuildMemberWarnOnConnectionStateMessage.h"
#include "../Messages/GuildMemberSetWarnOnConnectionMessage.h"
#include "../Messages/FriendWarnOnLevelGainStateMessage.h"
#include "../Messages/FriendWarnOnConnectionStateMessage.h"
#include "../Messages/FriendSetWarnOnConnectionMessage.h"
#include "../Messages/FriendSetWarnOnLevelGainMessage.h"
#include "../Messages/FriendUpdateMessage.h"
#include "../Messages/FriendAddedMessage.h"
#include "../Messages/FriendAddFailureMessage.h"
#include "../Messages/FriendAddRequestMessage.h"
#include "../Messages/FriendDeleteRequestMessage.h"
#include "../Messages/FriendDeleteResultMessage.h"
#include "../Messages/FriendsGetListMessage.h"
#include "../Messages/FriendsListMessage.h"
#include "../Messages/CharacterStatsListMessage.h"
#include "../Messages/MapComplementaryInformationsDataMessage.h"
#include "../Messages/GameRolePlayShowActorMessage.h"

#include "SubArea.h"
#include "Mount.h"
#include "ItemSet.h"
#include "Entity.h"
#include "Character.h"
#include "Session.h"

#endif