#ifndef __CONFIG_DEFAULTS__
#define __CONFIG_DEFAULTS__

#define LOCAL_DATABASE_HOST_STRING "LocalDatabaseHost"
#define LOCAL_DATABASE_HOST_DEFAULT "127.0.0.1"

#define LOCAL_DATABASE_NAME_STRING "LocalDatabaseName"
#define LOCAL_DATABASE_NAME_DEFAULT "desperion"

#define LOCAL_DATABASE_USER_STRING "LocalDatabaseUser"
#define LOCAL_DATABASE_USER_DEFAULT "root"

#define LOCAL_DATABASE_PASSWORD_STRING "LocalDatabasePassword"
#define LOCAL_DATABASE_PASSWORD_DEFAULT ""

#define LOCAL_DATABASE_PORT_STRING "LocalDatabasePort"
#define LOCAL_DATABASE_PORT_DEFAULT 3306

#define LOCAL_SERVER_PORT_STRING "LocalServerPort"
#define LOCAL_SERVER_PORT_DEFAULT 443

#define DISTANT_SERVER_PORT_STRING "DistantServerPort"
#define DISTANT_SERVER_PORT_DEFAULT 444

#define SERVER_MAINTENANCE_STRING "ServerMaintenance"
#define SERVER_MAINTENANCE_DEFAULT false

#endif